## 0. Load imports

In [2]:
## imports
import numpy as np
import pandas as pd

## print multiple things from same cell
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

## 0. Load data

In [3]:
## load data on 2020 crimes in DC
df = dc_crim_2020 = pd.read_csv(
    "https://opendata.arcgis.com/datasets/f516e0dd7b614b088ad781b0c4002331_2.csv"
)
dc_crim_2020.head()
dc_crim_2020.shape
dc_crim_2020.info()

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID
0,396217.89,138008.23,20143189,2020/10/07 05:06:33+00,2020/10/05 20:00:29+00,2020/10/07 03:11:00+00,1300 - 1699 BLOCK OF CONNECTICUT AVENUE NW,BURGLARY,OTHERS,MIDNIGHT,...,005502 1,5502.0,Precinct 14,DUPONT CIRCLE,396217.89,138008.23,38.909927,-77.043607,976657932,NaN
1,400594.00,139371.00,20019634,2020/02/02 00:38:51+00,2020/02/01 22:30:56+00,2020/02/01 23:14:15+00,900 - 999 BLOCK OF RHODE ISLAND AVENUE NE,THEFT/OTHER,OTHERS,EVENING,...,009102 4,9102.0,Precinct 72,NaN,400594.00,139371.00,38.922212,-76.993150,976657941,NaN
2,404064.01,139635.98,20022515,2020/02/06 19:38:30+00,2020/02/05 23:00:07+00,2020/02/06 19:48:32+00,3600 - 3799 BLOCK OF JAMISON STREET NE,THEFT F/AUTO,OTHERS,DAY,...,009000 2,9000.0,Precinct 139,NaN,404064.01,139635.98,38.924589,-76.953133,976657942,NaN
3,403340.00,132117.00,20085996,2020/06/10 17:01:07+00,2020/06/09 23:30:29+00,2020/06/10 10:50:38+00,2700 - 2799 BLOCK OF 32ND STREET SE,THEFT F/AUTO,OTHERS,DAY,...,007603 4,7603.0,Precinct 113,NaN,403340.00,132117.00,38.856859,-76.961519,976657945,NaN
4,397965.00,138634.00,20044480,2020/03/13 07:42:44+00,2020/03/13 07:07:01+00,NaN,800 - 899 BLOCK OF T STREET NW,THEFT F/AUTO,OTHERS,MIDNIGHT,...,004402 2,4402.0,Precinct 137,NaN,397965.00,138634.00,38.915570,-77.023465,976657959,NaN

(27932, 25)

<class 'pandas.DataFrame'>
RangeIndex: 27932 entries, 0 to 27931
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   X                     27932 non-null  float64
 1   Y                     27932 non-null  float64
 2   CCN                   27932 non-null  int64
 3   REPORT_DAT            27932 non-null  str
 4   START_DATE            27932 non-null  str
 5   END_DATE              24851 non-null  str
 6   BLOCK                 27932 non-null  str
 7   OFFENSE               27932 non-null  str
 8   METHOD                27932 non-null  str
 9   SHIFT                 27932 non-null  str
 10  WARD                  27932 non-null  int64
 11  ANC                   27932 non-null  str
 12  DISTRICT              27903 non-null  float64
 13  PSA                   27897 non-null  float64
 14  NEIGHBORHOOD_CLUSTER  27932 non-null  str
 15  BLOCK_GROUP           27931 non-null  str
 16  CENSUS_TRACT          27931 non-null  float64
 17  VOTING_PRECINCT       27932 non-null  str
 18  BID                   4658 non-null   str
 19  XBLOCK                27932 non-null  float64
 20  YBLOCK                27932 non-null  float64
 21  LATITUDE              27932 non-null  float64
 22  LONGITUDE             27932 non-null  float64
 23  OBJECTID              27932 non-null  int64
 24  OCTO_RECORD_ID        0 non-null      float64
dtypes: float64(10), int64(3), str(12)
memory usage: 5.3 MB

#### Warm-up: Ways to add 100 to column X

In [4]:
x_plus_hundred = df.copy()
x_plus_hundred["X"] = x_plus_hundred["X"] + 100

x_plus_hundred.head()

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BLOCK_GROUP,CENSUS_TRACT,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID
0,396317.89,138008.23,20143189,2020/10/07 05:06:33+00,2020/10/05 20:00:29+00,2020/10/07 03:11:00+00,1300 - 1699 BLOCK OF CONNECTICUT AVENUE NW,BURGLARY,OTHERS,MIDNIGHT,...,005502 1,5502.0,Precinct 14,DUPONT CIRCLE,396217.89,138008.23,38.909927,-77.043607,976657932,NaN
1,400694.00,139371.00,20019634,2020/02/02 00:38:51+00,2020/02/01 22:30:56+00,2020/02/01 23:14:15+00,900 - 999 BLOCK OF RHODE ISLAND AVENUE NE,THEFT/OTHER,OTHERS,EVENING,...,009102 4,9102.0,Precinct 72,NaN,400594.00,139371.00,38.922212,-76.993150,976657941,NaN
2,404164.01,139635.98,20022515,2020/02/06 19:38:30+00,2020/02/05 23:00:07+00,2020/02/06 19:48:32+00,3600 - 3799 BLOCK OF JAMISON STREET NE,THEFT F/AUTO,OTHERS,DAY,...,009000 2,9000.0,Precinct 139,NaN,404064.01,139635.98,38.924589,-76.953133,976657942,NaN
3,403440.00,132117.00,20085996,2020/06/10 17:01:07+00,2020/06/09 23:30:29+00,2020/06/10 10:50:38+00,2700 - 2799 BLOCK OF 32ND STREET SE,THEFT F/AUTO,OTHERS,DAY,...,007603 4,7603.0,Precinct 113,NaN,403340.00,132117.00,38.856859,-76.961519,976657945,NaN
4,398065.00,138634.00,20044480,2020/03/13 07:42:44+00,2020/03/13 07:07:01+00,NaN,800 - 899 BLOCK OF T STREET NW,THEFT F/AUTO,OTHERS,MIDNIGHT,...,004402 2,4402.0,Precinct 137,NaN,397965.00,138634.00,38.915570,-77.023465,976657959,NaN

## 1. Aggregation

### Example of grouping by one variable and doing one aggregation 

**Task**: find and print the number of unique offense types (`OFFENSE`) by ward (`WARD`)

In [5]:
df.groupby(["WARD"])["OFFENSE"].nunique()

WARD
1    9
2    9
3    8
4    8
5    9
6    9
7    9
8    9
Name: OFFENSE, dtype: int64

### Example of grouping by one variable and providing two summaries of the same variable

**Task**: previous showed number of offenses by ward but want to find out content of offenses in each ward; create an aggregation that summarizes both the number of unique offenses by ward and what those offenses are -- for instance, by pasting the unique offenses in that ward separated by the ";" (e.g., Theft; Burglary;...)

*Hint*: you can use the join command to paste together a list separated by some delimiter. 
    - The syntax, if we are using the comma delimiter, is: ", ".join(nameoflist)

In [10]:
two_sums = df.groupby("WARD").agg(
    n_unique=("OFFENSE", "nunique"),
    n_total=("OFFENSE", "count"),
    string=("OFFENSE", lambda x: ", ".join(sorted(set(x.astype(str))))),
)

In [11]:
two_sums

      n_unique  n_total                                             string
WARD
1            9     3542  ARSON, ASSAULT W/DANGEROUS WEAPON, BURGLARY, H...
2            9     4685  ARSON, ASSAULT W/DANGEROUS WEAPON, BURGLARY, H...
3            8     1709  ASSAULT W/DANGEROUS WEAPON, BURGLARY, HOMICIDE...
4            8     2703  ASSAULT W/DANGEROUS WEAPON, BURGLARY, HOMICIDE...
5            9     4395  ARSON, ASSAULT W/DANGEROUS WEAPON, BURGLARY, H...
6            9     3815  ARSON, ASSAULT W/DANGEROUS WEAPON, BURGLARY, H...
7            9     4148  ARSON, ASSAULT W/DANGEROUS WEAPON, BURGLARY, H...
8            9     2935  ARSON, ASSAULT W/DANGEROUS WEAPON, BURGLARY, H...

### Example of grouping by two variables 

**Task**: group by ward (`WARD`) and police shift (`SHIFT`) and find the offense that is most common in that ward and shift

In [15]:
df.groupby(["WARD", "SHIFT"]).agg(
    most_common=("OFFENSE", lambda x: x.value_counts().idxmax())
)

                              most_common
WARD SHIFT
1    DAY                      THEFT/OTHER
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
2    DAY                      THEFT/OTHER
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
3    DAY                      THEFT/OTHER
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
4    DAY                     THEFT F/AUTO
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
5    DAY                     THEFT F/AUTO
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
6    DAY                      THEFT/OTHER
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
7    DAY                     THEFT F/AUTO
     EVENING                  THEFT/OTHER
     MIDNIGHT                 THEFT/OTHER
8    DAY                     THEFT F/AUTO
     EVENING                  THEFT/OTHER
     MIDNIGHT  ASSAULT W/DANGEROUS WEAPON

## Summarizing over all rows or all columns (without grouping)

We can also use the `apply` function to summarize rows or columns efficiently

**Task**: find the mean lat and longitude in one line of code

In [39]:
df[["X", "Y"]].mean()

X    399389.539270
Y    137750.842027
dtype: float64

## 2. Creating new columns/transforming their type

### Simple filtering

`np.where` is in the numpy package (aliased as `np`) and operates similar to `ifelse` in R

But there is a built in pandas way to emulate this.

**Task**: create an indicator `is_theft` for any offense that contains the word "THEFT"
    
**Task**: create an indicator `is_theft_notmotor` for any offense that contains the word "THEFT" but does not contain the word "MOTOR"

In [18]:
df["is_theft"] = df["OFFENSE"].str.contains("THEFT")
df["is_theft_notmotor"] = df["OFFENSE"].str.contains("THEFT") & ~df[
    "OFFENSE"
].str.contains("MOTOR")

### np.select

**Task**: create a new variable, `offense_summary`, where you:
        
- Recode theft offenses that use a gun or knife as the method (`METHOD`) as: violent theft
- Recode non-theft offenses that use a gun or knife as the method as: violent other
- Recode all other as non-violent

In [49]:
conds = [
    df["METHOD"].isin(["GUN", "KNIFE"]) & df["is_theft"],
    df["METHOD"].isin(["GUN", "KNIFE"]) & ~df["is_theft"],
]
cats = ["VIOLENT THEFT", "VIOLENT OTHER"]

offense_summary = df.copy()
offense_summary["OFFENSE"] = np.select(conds, cats, default="NON-VIOLENT")

### map.recode

**Task**: recode shifts that are MIDNIGHT or EVENING as "nighttime"; code other shift to daytime

In [58]:
df["SHIFT"] = df["SHIFT"].map(
    {"MIDNIGHT": "nighttime", "EVENING": "nighttime", "DAY": "daytime"}
)

In [52]:
offense_summary

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,VOTING_PRECINCT,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID,is_theft,is_theft_notmotor
0,395578.0,137084.0,20173581,2020/12/07 00:18:08+00,2020/12/06 11:00:28+00,2020/12/06 18:30:36+00,916 - 999 BLOCK OF NEW HAMPSHIRE AVENUE NW,NON-VIOLENT,OTHERS,NaN,...,Precinct 3,NaN,395578.0,137084.0,38.901599,-77.050979,973009096,NaN,True,True
1,406683.0,137294.0,20123208,2020/08/29 03:10:30+00,2020/08/29 01:58:44+00,2020/08/29 02:29:37+00,934 - 1099 BLOCK OF EASTERN AVENUE NE,NON-VIOLENT,OTHERS,NaN,...,Precinct 95,NaN,406683.0,137294.0,38.903476,-76.922953,973009099,NaN,True,True
2,400930.0,134891.0,20146441,2020/10/13 17:02:37+00,2020/10/13 14:00:20+00,2020/10/13 14:15:44+00,1201 - 1249 BLOCK OF PENNSYLVANIA AVENUE SE,NON-VIOLENT,OTHERS,NaN,...,Precinct 91,CAPITOL HILL,400930.0,134891.0,38.881854,-76.989282,973009103,NaN,True,True
3,399759.0,138467.0,20066426,2020/05/02 15:43:07+00,2020/05/02 03:00:37+00,2020/05/02 14:00:42+00,200 - 299 BLOCK OF S STREET NE,NON-VIOLENT,OTHERS,NaN,...,Precinct 75,NaN,399759.0,138467.0,38.914068,-77.002779,973009105,NaN,True,True
4,402060.0,141604.0,20016295,2020/01/27 19:03:53+00,2020/01/27 18:32:21+00,2020/01/27 19:03:47+00,4300 - 4399 BLOCK OF 20TH STREET NE,NON-VIOLENT,OTHERS,NaN,...,Precinct 69,NaN,402060.0,141604.0,38.942325,-76.976238,973009118,NaN,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27927,402374.0,132186.0,10251445,2020/09/11 04:00:00+00,2010/09/02 04:00:00+00,2010/09/02 04:00:00+00,2300 - 2399 BLOCK OF AINGER PLACE SE,VIOLENT OTHER,GUN,NaN,...,Precinct 134,NaN,402374.0,132186.0,38.857483,-76.972648,973603803,NaN,False,False
27928,396168.0,137533.0,11139598,2020/08/24 04:00:00+00,2011/09/23 06:40:00+00,NaN,1900 - 1999 BLOCK OF M STREET NW,NON-VIOLENT,OTHERS,NaN,...,Precinct 17,GOLDEN TRIANGLE,396168.0,137533.0,38.905646,-77.044180,973603804,NaN,False,False
27929,398532.0,137185.0,20400937,2020/07/06 17:56:47+00,2020/06/25 14:00:00+00,2020/06/25 18:00:00+00,400 - 443 BLOCK OF K STREET NW,NON-VIOLENT,OTHERS,NaN,...,Precinct 1,MOUNT VERNON TRIANGLE CID,398532.0,137185.0,38.902518,-77.016924,973603824,NaN,True,True
27930,398336.0,140760.0,20033584,2020/02/24 23:41:38+00,2020/02/24 20:13:20+00,2020/02/24 20:15:44+00,3600 - 3627 BLOCK OF PARK PLACE NW,NON-VIOLENT,OTHERS,NaN,...,Precinct 43,NaN,398336.0,140760.0,38.934723,-77.019192,973603852,NaN,True,True
27931,398676.0,138855.0,20001553,2020/01/08 13:25:33+00,2020/01/03 16:53:56+00,2020/01/03 17:23:23+00,200 - 299 BLOCK OF ELM STREET NW,NON-VIOLENT,OTHERS,NaN,...,Precinct 20,NaN,398676.0,138855.0,38.917563,-77.015267,973603912,NaN,True,True

### Using built-in pandas methods

Another way of creating variables, used either alone or in combination with np.where and np.select is to use pandas built in `str` methods

Basic structure is: `df['namestringcol'].str.someoperation`

**Task**: using a `str` method, create a new column--`OFFENSE_NOSP`--that replaces spaces in the `OFFENSE` column with underscores

### Transforming column types

**Task**: check the type of the `START_DATE` column

**Task**: recast the `START_DATE` column to datetime, calling this `START_DATE_CLEAN`; coerce errors rather than cleaning the string; check the type of that new col

In [16]:
df["START_DATE_CLEAN"] = pd.to_datetime(df["START_DATE"], errors="coerce")

**Task:** print the min and max of `START_DATE_CLEAN`. What happens if you try to do this with `START_DATE`?

## 3. Row and column filtering

### Row subsetting

**Task**: filter to crime reports about theft using the `is_theft` definition and that are in ward 3

In [23]:
df[df["WARD"] == 3]

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID,START_DATE_CLEAN,is_theft,is_theft_notmotor
32,395002.0,139647.0,20120535,2020/08/23 21:28:52+00,2020/08/23 17:00:35+00,2020/08/23 19:00:24+00,2700 - 2799 BLOCK OF 29TH STREET NW,THEFT/OTHER,OTHERS,EVENING,...,NaN,395002.0,139647.0,38.924684,-77.057638,976658084,NaN,2020-08-23 17:00:35+00:00,True,True
35,394694.0,141367.0,20142437,2020/10/06 00:08:04+00,2020/10/05 01:21:57+00,2020/10/05 17:00:09+00,3900 - 3999 BLOCK OF CONNECTICUT AVENUE NW,THEFT F/AUTO,OTHERS,EVENING,...,NaN,394694.0,141367.0,38.940176,-77.061203,976658096,NaN,2020-10-05 01:21:57+00:00,True,True
39,395291.0,139866.0,20052264,2020/03/29 13:26:21+00,2020/03/29 11:30:31+00,2020/03/29 11:50:38+00,2600 - 2699 BLOCK OF GARFIELD STREET NW,THEFT/OTHER,OTHERS,DAY,...,NaN,395291.0,139866.0,38.926658,-77.054307,976658114,NaN,2020-03-29 11:30:31+00:00,True,True
43,393189.0,142005.0,20068220,2020/05/06 14:45:47+00,2020/05/05 14:00:27+00,2020/05/05 15:00:58+00,4336 - 4347 BLOCK OF WISCONSIN AVENUE NW,MOTOR VEHICLE THEFT,OTHERS,DAY,...,NaN,393189.0,142005.0,38.945913,-77.078569,976658131,NaN,2020-05-05 14:00:27+00:00,True,False
48,393424.0,143681.0,20013517,2020/01/23 14:00:25+00,2020/01/22 20:00:12+00,2020/01/23 11:00:56+00,3741 - 3899 BLOCK OF MILITARY ROAD NW,THEFT F/AUTO,OTHERS,DAY,...,NaN,393424.0,143681.0,38.961013,-77.075874,976658141,NaN,2020-01-22 20:00:12+00:00,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27798,394335.0,142159.0,20005944,2020/01/11 05:54:27+00,2017/07/01 04:01:36+00,2018/08/01 03:59:12+00,4400 - 4499 BLOCK OF CONNECTICUT AVENUE NW,SEX ABUSE,GUN,MIDNIGHT,...,NaN,394335.0,142159.0,38.947309,-77.065351,977252890,NaN,2017-07-01 04:01:36+00:00,False,False
27822,393262.0,142045.0,20127923,2020/09/07 17:36:06+00,2020/09/07 13:50:12+00,2020/09/07 16:30:13+00,3900 - 3999 BLOCK OF YUMA STREET NW,THEFT F/AUTO,OTHERS,DAY,...,NaN,393262.0,142045.0,38.946274,-77.077727,977253083,NaN,2020-09-07 13:50:12+00:00,True,True
27835,392607.0,143559.0,20401055,2020/07/28 20:55:20+00,2020/07/27 18:14:00+00,2020/07/27 18:20:00+00,5300 - 5399 BLOCK OF WISCONSIN AVENUE NW,THEFT/OTHER,OTHERS,EVENING,...,NaN,392607.0,143559.0,38.959907,-77.085300,977253271,NaN,2020-07-27 18:14:00+00:00,True,True
27920,393070.0,142276.0,20007861,2020/01/14 02:24:36+00,2020/01/14 01:28:15+00,NaN,4500 - 4537 BLOCK OF WISCONSIN AVENUE NW,MOTOR VEHICLE THEFT,OTHERS,EVENING,...,NaN,393070.0,142276.0,38.948354,-77.079945,977253772,NaN,2020-01-14 01:28:15+00:00,True,False
27930,394335.0,142159.0,20018868,2020/01/31 19:36:51+00,2019/12/14 17:00:23+00,2020/01/31 19:37:12+00,4400 - 4499 BLOCK OF CONNECTICUT AVENUE NW,MOTOR VEHICLE THEFT,OTHERS,DAY,...,NaN,394335.0,142159.0,38.947309,-77.065351,977253826,NaN,2019-12-14 17:00:23+00:00,True,False

In [29]:
df[(df["is_theft"]) & (df["WARD"] == 3)]

,X,Y,CCN,REPORT_DAT,START_DATE,END_DATE,BLOCK,OFFENSE,METHOD,SHIFT,...,BID,XBLOCK,YBLOCK,LATITUDE,LONGITUDE,OBJECTID,OCTO_RECORD_ID,START_DATE_CLEAN,is_theft,is_theft_notmotor
32,395002.0,139647.0,20120535,2020/08/23 21:28:52+00,2020/08/23 17:00:35+00,2020/08/23 19:00:24+00,2700 - 2799 BLOCK OF 29TH STREET NW,THEFT/OTHER,OTHERS,EVENING,...,NaN,395002.0,139647.0,38.924684,-77.057638,976658084,NaN,2020-08-23 17:00:35+00:00,True,True
35,394694.0,141367.0,20142437,2020/10/06 00:08:04+00,2020/10/05 01:21:57+00,2020/10/05 17:00:09+00,3900 - 3999 BLOCK OF CONNECTICUT AVENUE NW,THEFT F/AUTO,OTHERS,EVENING,...,NaN,394694.0,141367.0,38.940176,-77.061203,976658096,NaN,2020-10-05 01:21:57+00:00,True,True
39,395291.0,139866.0,20052264,2020/03/29 13:26:21+00,2020/03/29 11:30:31+00,2020/03/29 11:50:38+00,2600 - 2699 BLOCK OF GARFIELD STREET NW,THEFT/OTHER,OTHERS,DAY,...,NaN,395291.0,139866.0,38.926658,-77.054307,976658114,NaN,2020-03-29 11:30:31+00:00,True,True
43,393189.0,142005.0,20068220,2020/05/06 14:45:47+00,2020/05/05 14:00:27+00,2020/05/05 15:00:58+00,4336 - 4347 BLOCK OF WISCONSIN AVENUE NW,MOTOR VEHICLE THEFT,OTHERS,DAY,...,NaN,393189.0,142005.0,38.945913,-77.078569,976658131,NaN,2020-05-05 14:00:27+00:00,True,False
48,393424.0,143681.0,20013517,2020/01/23 14:00:25+00,2020/01/22 20:00:12+00,2020/01/23 11:00:56+00,3741 - 3899 BLOCK OF MILITARY ROAD NW,THEFT F/AUTO,OTHERS,DAY,...,NaN,393424.0,143681.0,38.961013,-77.075874,976658141,NaN,2020-01-22 20:00:12+00:00,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27779,394085.0,143798.0,20138658,2020/09/28 21:52:08+00,2020/09/28 18:30:28+00,2020/09/28 19:30:31+00,3300 - 3599 BLOCK OF LEGATION STREET NW,THEFT F/AUTO,OTHERS,EVENING,...,NaN,394085.0,143798.0,38.962072,-77.068249,977252703,NaN,2020-09-28 18:30:28+00:00,True,True
27822,393262.0,142045.0,20127923,2020/09/07 17:36:06+00,2020/09/07 13:50:12+00,2020/09/07 16:30:13+00,3900 - 3999 BLOCK OF YUMA STREET NW,THEFT F/AUTO,OTHERS,DAY,...,NaN,393262.0,142045.0,38.946274,-77.077727,977253083,NaN,2020-09-07 13:50:12+00:00,True,True
27835,392607.0,143559.0,20401055,2020/07/28 20:55:20+00,2020/07/27 18:14:00+00,2020/07/27 18:20:00+00,5300 - 5399 BLOCK OF WISCONSIN AVENUE NW,THEFT/OTHER,OTHERS,EVENING,...,NaN,392607.0,143559.0,38.959907,-77.085300,977253271,NaN,2020-07-27 18:14:00+00:00,True,True
27920,393070.0,142276.0,20007861,2020/01/14 02:24:36+00,2020/01/14 01:28:15+00,NaN,4500 - 4537 BLOCK OF WISCONSIN AVENUE NW,MOTOR VEHICLE THEFT,OTHERS,EVENING,...,NaN,393070.0,142276.0,38.948354,-77.079945,977253772,NaN,2020-01-14 01:28:15+00:00,True,False
27930,394335.0,142159.0,20018868,2020/01/31 19:36:51+00,2019/12/14 17:00:23+00,2020/01/31 19:37:12+00,4400 - 4499 BLOCK OF CONNECTICUT AVENUE NW,MOTOR VEHICLE THEFT,OTHERS,DAY,...,NaN,394335.0,142159.0,38.947309,-77.065351,977253826,NaN,2019-12-14 17:00:23+00:00,True,False

### Column subsetting

**Task**: select two columns--`START_DATE` and `END_DATE`--and print the head of the dataframe

In [28]:
df[["START_DATE", "END_DATE"]]

                   START_DATE                END_DATE
0      2020/10/05 20:00:29+00  2020/10/07 03:11:00+00
1      2020/02/01 22:30:56+00  2020/02/01 23:14:15+00
2      2020/02/05 23:00:07+00  2020/02/06 19:48:32+00
3      2020/06/09 23:30:29+00  2020/06/10 10:50:38+00
4      2020/03/13 07:07:01+00                     NaN
...                       ...                     ...
27927  2020/09/11 18:01:25+00  2020/09/11 19:30:49+00
27928  2020/09/14 04:00:11+00  2020/09/14 06:00:27+00
27929  2020/08/28 20:26:16+00  2020/08/28 20:40:53+00
27930  2019/12/14 17:00:23+00  2020/01/31 19:37:12+00
27931  2020/10/21 05:30:40+00  2020/10/21 05:32:41+00

[27932 rows x 2 columns]

**Task**: use list comprehension to automate this a bit and select all columns with the word "DATE" in the name; print the head of the dataframe

In [32]:
df[[col for col in df.columns if "DATE" in col]]

,START_DATE,END_DATE,START_DATE_CLEAN
0,2020/10/05 20:00:29+00,2020/10/07 03:11:00+00,2020-10-05 20:00:29+00:00
1,2020/02/01 22:30:56+00,2020/02/01 23:14:15+00,2020-02-01 22:30:56+00:00
2,2020/02/05 23:00:07+00,2020/02/06 19:48:32+00,2020-02-05 23:00:07+00:00
3,2020/06/09 23:30:29+00,2020/06/10 10:50:38+00,2020-06-09 23:30:29+00:00
4,2020/03/13 07:07:01+00,NaN,2020-03-13 07:07:01+00:00
...,...,...,...
27927,2020/09/11 18:01:25+00,2020/09/11 19:30:49+00,2020-09-11 18:01:25+00:00
27928,2020/09/14 04:00:11+00,2020/09/14 06:00:27+00,2020-09-14 04:00:11+00:00
27929,2020/08/28 20:26:16+00,2020/08/28 20:40:53+00,2020-08-28 20:26:16+00:00
27930,2019/12/14 17:00:23+00,2020/01/31 19:37:12+00,2019-12-14 17:00:23+00:00
27931,2020/10/21 05:30:40+00,2020/10/21 05:32:41+00,2020-10-21 05:30:40+00:00

**Task**: filter reports of crime in `START_DATE_CLEAN` before May 2020 and that are located in ward 1; select the ward and `START_DATE` column and print a random sample of rows

In [36]:
df[(df["START_DATE_CLEAN"] < "2020-05-01") & (df["WARD"] == 1)][
    ["WARD", "START_DATE"]
].sample(10)

       WARD              START_DATE
27528     1  2020/02/06 19:04:04+00
18674     1  2020/04/07 21:14:58+00
24970     1  2020/02/01 17:00:49+00
1345      1  2020/02/14 00:24:21+00
24767     1  2020/02/24 20:13:20+00
1131      1  2020/02/29 08:05:27+00
217       1  2020/04/10 21:00:28+00
15694     1  2020/02/05 23:30:54+00
13177     1  2020/01/04 02:22:14+00
220       1  2020/04/22 16:10:39+00